version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -U rogerlinux"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: sh -c "npm run typeorm migration:run -- -d src/data-source && npm start"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  node_modules:
